language: python
python:
    - "2.7"

# command to install dependencies
install:
    - pip install . --use-mirrors
    - pip install coveralls --use-mirrors

# command to run tests
script:
    - python setup.py nosetests
    - nosetests --with-coverage --cover-erase --cover-package=formatter

after_success:
    - coveralls

