# Config file for automatic testing at travis-ci.org

sudo: false
language: python
python: 3.6
env:
    - TOX_ENV=docs
    - TOX_ENV=py27 
    - TOX_ENV=py35 
    - TOX_ENV=py36 

# command to install dependencies, e.g. pip install -r requirements.txt 
install:
    - pip install tox

script:
    - tox -e $TOX_ENV

notifications:
  email:
    on_success: never
    on_failure: change

